### ISSUE TITLE
acc - rutine

### ISSUE THREAD

**Issue by ssilje** [ssilje/S2S-download#30]
https://github.com/ssilje/S2S-download/blob/59efc500db5573518e228aab341529e02261c599/S2S/scoring.py#L91

Skal det vere ufunk her (og ikkje centered_acc)?

**Comment by ssilje** [comment]
@henrikauestad

**Comment by ssilje** [comment]
pull request

**Comment by henrikauestad** [comment]
#31 this update should fix the issue

**Comment by henrikauestad** [comment]
I am closing this issue now
