### ISSUE TITLE
convert from K to C

### ISSUE THREAD

**Issue by ssilje** [ssilje/S2S-download#32]
https://github.com/ssilje/S2S-download/blob/7f3d47dd70115a3ddcce879342cf9ece98421288/S2S/process.py#L183

Blir dette gjort for alle variablene?

**Comment by ssilje** [comment]
@henrikauestad

**Comment by henrikauestad** [comment]
Oi, ja. Fikser det!

**Comment by henrikauestad** [comment]
#33 possible fix for this issue.
