### ISSUE TITLE
Suppress writing .idx files when using cfgrib

### ISSUE THREAD

**Issue by olewu** [ssilje/S2S-download#34]
https://github.com/ssilje/S2S-download/blob/d2fed62aa602c2f8e17f526b8850e90726298bc9/S2S/data_handler.py#L292

To prevent writing of the index files when opening a dataset, one can set the backend keyword argument 'indexpath' with an empty string like this:

`open_data = xr.open_dataset(self.in_path+filename, engine=engine, backend_kwargs={'indexpath':''})`

This will only work if `engine='cfgrib'` though. If not, the loading fails.

I found this in the cfgrib documentation here: [https://github.com/ecmwf/cfgrib](https://github.com/ecmwf/cfgrib)

**Comment by ssilje** [comment]
@henrikauestad

**Comment by henrikauestad** [comment]
Great, I will implement this.

**Comment by henrikauestad** [comment]
I see that you already did
