### ISSUE TITLE
Computation of climatology in S2S.process.Forecast

### ISSUE THREAD

**Issue by henrikauestad** [ssilje/S2S-download#36]
@olewu

From S2S.process.Forecast:
            # climatologies saved in hc_ref.
            # subtract clim mean and divide by clim std.
            # climatology files are extended to a value each year are (should be) the same for every year
            # so it should be possible to take the mean over all hindcast years (try to find better solution): 
            self.data_anom = (self.data.groupby('time.dayofyear') - hc_ref.mean.groupby('time.dayofyear').mean())
            self.data_a = self.data_anom.groupby('time.dayofyear')/hc_ref.std.groupby('time.dayofyear').mean()

I am a bit unsure whether this approach is the same as computing the climatology over the full hindcast period. Given 20 years of hindcast: I'm thinking something in the direction of; as each year is represented 19 times (because of the cross-validation) then taking hc_ref.mean.groupby('time.dayofyear').mean() now divides the sum of the means with 20, but the years are only represented 19 times. I am not sure if it matters, and the error (if it gives an error) is most likely very small (at least for a 20 year hindcast period).

Another approach that we would know to be correct is substituting  
    hc_ref.mean.groupby('time.dayofyear').mean() with hc_ref.data.groupby('time.dayofyear').mean()
and 
    hc_ref.std.groupby('time.dayofyear').mean() with hc_ref.data.groupby('time.dayofyear').std()

**Comment by ssilje** [comment]
@henrikauestad

**Comment by henrikauestad** [comment]
Solution to this:
Allow for cross-validation in climatology computation in hindcast. Will look into it.

**Comment by henrikauestad** [comment]
@olewu the changes suggested in #43 allows for cross-validation in the computation of hindcast climatology
